image: eclipse-temurin:8
stages:
  - test

variables:
  GRADLE_ARGS: --no-daemon --stacktrace --warning-mode=all
  DEBIAN_FRONTEND: noninteractive

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apt-get update && apt-get install -y git

.tests:
  stage: test
  script:
    - ./gradlew ${GRADLE_ARGS} check

tests:jdk-8:
  extends: .tests

tests:jdk-11:
  extends: .tests
  image: eclipse-temurin:11

tests:jdk-17:
  extends: .tests
  image: eclipse-temurin:17

tests:jdk-21:
  extends: .tests
  image: eclipse-temurin:21