image: eclipse-temurin:8
stages:
  - test
  - deploy

variables:
  GRADLE_ARGS: --no-daemon --stacktrace --warning-mode=all
  DEBIAN_FRONTEND: noninteractive

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apt-get update && apt-get install -y git

.tests:
  stage: test
  script:
    - ./gradlew ${GRADLE_ARGS} check

tests:jdk-8:
  extends: .tests

tests:jdk-11:
  extends: .tests
  image: eclipse-temurin:11

tests:jdk-17:
  extends: .tests
  image: eclipse-temurin:17

tests:jdk-21:
  extends: .tests
  image: eclipse-temurin:21

publish:
  stage: deploy
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - apt-get update && apt-get install -y git

    - openssl aes-256-cbc -pass "env:ENCRYPTION_PASSWORD" -d -a -md md5 -in secring.gpg.enc       -out secring.gpg
    - openssl aes-256-cbc -pass "env:ENCRYPTION_PASSWORD" -d -a -md md5 -in pubring.gpg.enc       -out pubring.gpg
    - openssl aes-256-cbc -pass "env:ENCRYPTION_PASSWORD" -d -a -md md5 -in gradle.properties.enc -out gradle.properties
  script:
    - ./gradlew ${GRADLE_OPTIONS} publish
  only:
    - main@stups/prob/xml2b